[CELEBORN] CHCelebornColumnarShuffleWriter supports celeborn.client.spark.shuffle.writer to use external sort shuffle in ClickHouse backend
apache/incubator-gluten pull request #6432
Opened 2024-07-12 09:16 UTC by SteNicholas

## What changes were proposed in this pull request?

`CHCelebornColumnarShuffleWriter` supports `celeborn.client.spark.shuffle.writer` to use external sort shuffle in ClickHouse backend.

## How was this patch tested?

CI.

2024-07-12 09:18 UTC, SteNicholas commented
Ping @taiyang-li, @liuneng1994, @kerwin-zk.

2024-07-12 09:23 UTC, SteNicholas commented
Ping @taiyang-li, @liuneng1994, @kerwin-zk.

2024-07-12 09:33 UTC, liuneng1994 approved these changes
LGTM

2024-07-12 10:22 UTC, taiyang-li requested changes

2024-07-12 10:22 UTC, taiyang-li commented on gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriter.scala
> +        if (nativeShuffleWriter == -1L) {
better to wrap below initializing codes in a function to make current loop cleaner.

2024-07-13 07:57 UTC, SteNicholas commented
@taiyang-li, @liuneng1994, I have addressed @taiyang-li comments. PTAL.

2024-07-13 08:36 UTC, SteNicholas commented
@taiyang-li, @liuneng1994, @kerwin-zk, I have addressed comments of @taiyang-li. PTAL.

2024-07-15 02:28 UTC, taiyang-li approved these changes
LGTM

2024-07-15 02:29 UTC, merged